### ISSUE TITLE
ack ignores a folder

### ISSUE THREAD

**Issue by davidhq** [petdance/ack2#537] opened 2015-03-12 23:36 UTC
Hi, I have some problems in `ack 2.14`:

```
david@eclipse:~/Projects/booktical (master)$ ack "Database configuration specifies nonexistent driver"
david@eclipse:~/Projects/booktical (master)$ ack "nonexistent driver"
david@eclipse:~/Projects/booktical (master)$ ack --js "nonexistent driver"
david@eclipse:~/Projects/booktical (master)$ ack "nonexistent"
david@eclipse:~/Projects/booktical (master)$ cd node_modules
david@eclipse:~/Projects/booktical/node_modules (master)$ ack "nonexistent"
active_record/lib/error.js
36:	this.message = "Database configuration specifies nonexistent driver: '"+ driver +"'";
```

Any explanation for this? I don't have `node_modules` ignored:

```
--type-add
ruby=.builder,.feature
--type-set
rackup=.ru
--type-set
haml=.haml
--type-add
php=.phtml
--type-set
jsx=.jsx
--type-set
markdown=.markdown,.md,.mdown
--type-set=cache=.cache
--ignore-dir=.idea
--ignore-dir=tmp
--ignore-dir=photos
--nocache
--nocss
```

**Comment by hoelzro** [comment] 2015-03-12 23:44
@davidhq If you look at the output of `ack --dump`, you'll notice that `node_modules` is ignored by default.

**Comment by davidhq** [comment] 2015-03-12 23:54
Aha ok, thank you.. this is probably a good default, yes...

Can I somehow override this from the command line when I need to do it?

**Comment by hoelzro** [comment] 2015-03-12 23:56
Yes!  You can use `--noignore-dir=node_modules`.  If you're curious about other ways to use ignore, you can find out about it in `ack --man`.

**Comment by davidhq** [comment] 2015-03-13 11:17
Thank you for these tips!

**Comment by hoelzro** [comment] 2015-03-13 11:41
You're very welcome!

**Comment by hoelzro** [comment] 2015-03-24 00:52
I'm going to close this as a duplicate of #524

**Closed by hoelzro** 2015-03-24 00:52 UTC
