### ISSUE TITLE
the -l switches changes results

### ISSUE THREAD

**Issue by rjbs** [petdance/ack2#571] opened 2015-09-22 19:26 UTC
I was surprised to find that `-l` changes the set of matches.

```
~/code/perl5$ ack '^-- $' AUTHORS
--
~/code/perl5$ ack -l '^-- $' AUTHORS
```

In other words, I get results if I _don't_ pass `-l, but no results if I _do_.

ack 2.14
Running under Perl 5.23.3 at /Users/rjbs/.plenv/versions/23.3/bin/perl5.23.3

**Comment by rjbs** [comment] 2015-09-22 19:37
```
15:28 <haarg> work on 2.12, fails on 2.14
15:33 <@rjbs> Hm.
15:34 <@rjbs> The pattern matters too, so I've been assuming it's a change to
              how pattern is used.
15:35 <@rjbs> like: ack -l . AUTHORS <-- fine
```

**Comment by hoelzro** [comment] 2015-09-22 19:44
@rjbs This appears to be fixed in Git HEAD:

    [git:(HEAD detached at v5.22.0)] [14:42:09] rob@lepus ~/freezer/perl $ ~/projects/ack2/garage/ack-2.14 '^-- $' AUTHORS
    -- 
    [git:(HEAD detached at v5.22.0)] [14:42:20] rob@lepus ~/freezer/perl $ ~/projects/ack2/garage/ack-2.14 '^-- $' AUTHORS -l
    [git:(HEAD detached at v5.22.0)] [14:42:22] rob@lepus ~/freezer/perl $ ack '^-- $' AUTHORS                                
    -- 
    [git:(HEAD detached at v5.22.0)] [14:42:28] rob@lepus ~/freezer/perl $ ack '^-- $' AUTHORS -l 
    AUTHORS

**Comment by rjbs** [comment] 2015-09-22 19:45
@haarg has traced this to b3617f1f9cb1edf5290c046ace76ea29340e9d6a

This change reads the whole file, then scans it at once, but otherwise all patterns were being checked linewise.  This means that `^` and `$` are effectively different if the "optimized" version is being used.  

This optimization will break many possible patterns.  While the one in my example, `^-- $` would be fixed by adding `/m` to the regex (and, indeed, works if I pass `(?m)^-- $`, there are others that wouldn't be fixed.

```
~/code/perl5$ echo "fo\n\n\noo" > file
~/code/perl5$ ack 'fo\s+oo' file
~/code/perl5$ ack -l 'fo\s+oo' file
file
~/code/perl5$ ack -l '(?m)fo\s+oo' file
file
```

**Comment by hoelzro** [comment] 2015-09-22 19:45
Duplicate of #491 and #498

**Comment by rjbs** [comment] 2015-09-22 19:46
Thanks.  I didn't find those tickets because I looked for open tickets, since the bug is still alive in latest release.

**Comment by rjbs** [comment] 2015-09-22 19:47
If the fix is meant to be 17504aa361eef269c57f43c21e16d1705cd1e7c0 please note my comment above about how this is not making the "optimization" equivalent to the normal behavior.

**Comment by hoelzro** [comment] 2015-09-22 19:49
@rjbs Agreed; that issue was also pointed out in #562.  It looks like we'll have to rip that optimization out =(

**Comment by hoelzro** [comment] 2015-11-09 15:12
@rjbs This should now be fixed; please test out git HEAD and let me know if you find any more odd behavior!

**Closed** 2017-04-22 03:23 UTC
Labels: ack3, bug, PRIORITY 1
