### ISSUE TITLE
--pager="less -R" = command not found

### ISSUE THREAD

**Issue by jeffmacdonald** [petdance/ack2#600] opened 2016-05-26 18:19 UTC
If you add --pager="less -R" to your .ackrc file and the run it  you get something like this:

(venv) mbp0 AWS-43 $ ack TODO
sh: less -R: command not found

**Comment by hoelzro** [comment] 2016-05-27 01:15
Hi @jeffmacdonald, thanks for the report!  This is duplicate of #447; you can solve the issue by omitting the quotes around `less -R`.

**Closed by hoelzro** 2016-05-27 01:15 UTC

**Comment by hoelzro** [comment] 2016-05-27 01:19
I filed an issue #601 to document the options.

**Comment by jeffmacdonald** [comment] 2016-05-27 11:50
Thanks for the info!
